[package]
name = "kiley"
version = "0.1.0"
authors = ["ban-m <ban-m@g.ecc.u-tokyo.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poa_hmm = {git = "https://github.com/ban-m/partial_order_alignment.git"}
clap = "*"
bio = "*"
rand = "*"
rand_xoshiro = "*"

[dev-dependencies]
rayon = "*"
