[package]
name = "kiley"
version = "0.1.0"
authors = ["ban-m <ban-m@g.ecc.u-tokyo.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poa_hmm = {version = "0.2.0", git = "https://github.com/ban-m/partial_order_alignment.git", branch="master", features = ["poa_simd"]}
clap = "2.33"
rand = "*"
rand_xoshiro = "*"
log = "0.4.14"
bytecount = "*"

[dev-dependencies]
rayon = "1.3.1"
